# Generated by Django 6.0.3 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guest_name',
            field=models.CharField(default='guest', max_length=100),
        ),
    ]
