# Generated by Django 6.0.3 on 2026-03-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0004_bookings_guest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='bookings',
            new_name='booking_dates',
        ),
    ]
