# Generated by Django 6.0.3 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0005_rename_bookings_bookings_booking_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_dates',
        ),
        migrations.AddField(
            model_name='bookings',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='check_out',
            field=models.DateField(null=True),
        ),
    ]
